/*
 * This file is generated by jOOQ.
 */
package code.craft.documents.db;


import code.craft.documents.db.tables.DocumentInfo;
import code.craft.documents.db.tables.records.DocumentInfoRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * docup.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DocumentInfoRecord> KEY_DOCUMENT_INFO_PRIMARY = Internal.createUniqueKey(DocumentInfo.DOCUMENT_INFO, DSL.name("KEY_document_info_PRIMARY"), new TableField[] { DocumentInfo.DOCUMENT_INFO.ID }, true);
}
