/*
 * This file is generated by jOOQ.
 */
package code.craft.documents.db;


import code.craft.documents.db.tables.DocumentInfo;


/**
 * Convenience access to all tables in docup.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>docup.document_info</code>.
     */
    public static final DocumentInfo DOCUMENT_INFO = DocumentInfo.DOCUMENT_INFO;
}
